### ISSUE TITLE
dump process

### ISSUE THREAD

**Issue by DevX-Cipher** [riesha/smbios-dumper#1]
Regrettably, despite diligent efforts, I encountered difficulties compiling the Rust code due to the usage of unstable features not supported on the stable release channel. Consequently, I resorted to implementing the functionality in C++, yet encountered a setback wherein the BIOS dump generated by the C++ code lacks completeness, failing to encompass the entire 16MB BIOS file. This impediment hinders the comprehensive extraction of BIOS data, prompting the pursuit of a solution to ensure the entirety of the BIOS is successfully dumped

**Comment by riesha** [comment]
You should be able to compile this by just installing the nightly toolchain. This is also not a *BIOS* dumper but an *SMBIOS* dumper which contains hardware information, if you are looking for a c implementation of a similar tool, check out dmidecode https://github.com/mirror/dmidecode

**Comment by DevX-Cipher** [comment]
this does not dump the BIOS just give information

**Comment by riesha** [comment]
> this does not dump the BIOS just give information

Yes, my tool does the same thing while also allowing you to dump all of that information into a binary dump file.

**Comment by DevX-Cipher** [comment]
what do you mean dmidecode does not dump all information into a binary file at all also your code needs to be fixed as well I tried compiling and it still fails
